import { Component } from '@angular/core';
import { TableComponent } from '../table/table.component';
import { HeaderComponent } from '../header/header.component';
import { TableData } from '../../interfaces/table-data.interface';
import { SidebarComponent } from '../sidebar/sidebar.component';

@Component({
  selector: 'app-homepage',
  imports: [TableComponent, HeaderComponent, SidebarComponent],
  templateUrl: './homepage.component.html',
  styleUrl: './homepage.component.scss',
})
export class HomepageComponent {
  salesData: TableData[] = [
    {
      orderNumber: '234542213',
      client: 'Agritech Srl',
      agent: 'Georgescu Dan',
      data: '10 Iunie 2025',
      zone: 'Brăila',
      status: 'Blocat',
      reason: 'Credit',
      responsive: 'Mădălina Panait',
      lockDuration: '24 min',
      partialDelivery: 'Da',
      totalBlockage: '64 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
          warning: true,
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '234542214',
      client: 'GreenFarm SRL',
      agent: 'Popescu Andrei',
      data: '11 Iunie 2025',
      zone: 'Galați',
      status: 'În așteptare',
      reason: 'Document lipsă',
      responsive: 'Ionuț Ionescu',
      lockDuration: '15 min',
      partialDelivery: 'Nu',
      totalBlockage: '15 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '234542215',
      client: 'EcoAgro Import',
      agent: 'Dobre Maria',
      data: '12 Iunie 2025',
      zone: 'Iași',
      status: 'Blocat',
      reason: 'Depășire termen',
      responsive: 'Anca Vasile',
      lockDuration: '32 min',
      partialDelivery: 'Da',
      totalBlockage: '82 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '234542216',
      client: 'Agrosem Distributie',
      agent: 'Radu Marius',
      data: '12 Iunie 2025',
      zone: 'Cluj',
      status: 'Finalizat',
      reason: '-',
      responsive: 'Corina Dima',
      lockDuration: '0 min',
      partialDelivery: 'Nu',
      totalBlockage: '0 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '234542217',
      client: 'Ferma Nord',
      agent: 'Enache Irina',
      data: '13 Iunie 2025',
      zone: 'Botoșani',
      status: 'Blocat',
      reason: 'Stoc insuficient',
      responsive: 'Diana Preda',
      lockDuration: '48 min',
      partialDelivery: 'Da',
      totalBlockage: '110 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '234542218',
      client: 'Agroserv SRL',
      agent: 'Munteanu Silviu',
      data: '13 Iunie 2025',
      zone: 'Bacău',
      status: 'Blocat',
      reason: 'Neconfirmare client',
      responsive: 'Ramona Chiriac',
      lockDuration: '20 min',
      partialDelivery: 'Nu',
      totalBlockage: '45 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '234542219',
      client: 'Seminte Premium',
      agent: 'Ilie Gabriel',
      data: '14 Iunie 2025',
      zone: 'Suceava',
      status: 'În așteptare',
      reason: 'Verificare plată',
      responsive: 'Roxana Nistor',
      lockDuration: '10 min',
      partialDelivery: 'Nu',
      totalBlockage: '10 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '234542220',
      client: 'Tractor Line SRL',
      agent: 'Pop Iulian',
      data: '14 Iunie 2025',
      zone: 'Arad',
      status: 'Finalizat',
      reason: '-',
      responsive: 'Larisa Cristea',
      lockDuration: '0 min',
      partialDelivery: 'Nu',
      totalBlockage: '0 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '234542221',
      client: 'FarmExpert Solutions',
      agent: 'Stoica Adela',
      data: '15 Iunie 2025',
      zone: 'Constanța',
      status: 'Blocat',
      reason: 'Restanțe',
      responsive: 'Teodor Mărginean',
      lockDuration: '36 min',
      partialDelivery: 'Da',
      totalBlockage: '70 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '234542222',
      client: 'AgroMarket SRL',
      agent: 'Chiriță Bogdan',
      data: '15 Iunie 2025',
      zone: 'Timișoara',
      status: 'Blocat',
      reason: 'Limită depășită',
      responsive: 'Simona Marin',
      lockDuration: '18 min',
      partialDelivery: 'Nu',
      totalBlockage: '18 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
  ];
  salesTitle: string = 'Vanzari';
  purchasesData: TableData[] = [
    {
      orderNumber: '876512301',
      client: 'Furnizor AgroVest',
      agent: 'Rusu Mihai',
      data: '05 Iunie 2025',
      zone: 'Sibiu',
      status: 'Blocat',
      reason: 'Factura lipsă',
      responsive: 'Elena Pascu',
      lockDuration: '28 min',
      partialDelivery: 'Nu',
      totalBlockage: '72 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '876512302',
      client: 'SemPlus Distribution',
      agent: 'Matei Cristian',
      data: '06 Iunie 2025',
      zone: 'Oradea',
      status: 'Finalizat',
      reason: '-',
      responsive: 'Cristina Sava',
      lockDuration: '0 min',
      partialDelivery: 'Nu',
      totalBlockage: '0 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '876512303',
      client: 'FermaPartener',
      agent: 'Tănase Florin',
      data: '07 Iunie 2025',
      zone: 'Târgu Mureș',
      status: 'În așteptare',
      reason: 'Aprobări interne',
      responsive: 'Raluca Lungu',
      lockDuration: '12 min',
      partialDelivery: 'Nu',
      totalBlockage: '12 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '876512304',
      client: 'Magazin Utilaje SRL',
      agent: 'Drăghici Alina',
      data: '08 Iunie 2025',
      zone: 'Reșița',
      status: 'Blocat',
      reason: 'Stoc indisponibil',
      responsive: 'Mihai Pătru',
      lockDuration: '40 min',
      partialDelivery: 'Da',
      totalBlockage: '90 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '876512305',
      client: 'DistribFarm Plus',
      agent: 'Costache Laura',
      data: '09 Iunie 2025',
      zone: 'Tulcea',
      status: 'Blocat',
      reason: 'Neconfirmare cantitate',
      responsive: 'Oana Stanciu',
      lockDuration: '30 min',
      partialDelivery: 'Nu',
      totalBlockage: '55 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '876512306',
      client: 'AgroVest Solutions',
      agent: 'Mihail Dumitrescu',
      data: '10 Iunie 2025',
      zone: 'Slatina',
      status: 'Finalizat',
      reason: '-',
      responsive: 'Gabriel Udrea',
      lockDuration: '0 min',
      partialDelivery: 'Da',
      totalBlockage: '0 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
          warning: true,
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '876512307',
      client: 'EuroAgro Trade',
      agent: 'Carmen Apostol',
      data: '11 Iunie 2025',
      zone: 'Pitești',
      status: 'Blocat',
      reason: 'Aviz greșit',
      responsive: 'Nicoleta Toma',
      lockDuration: '22 min',
      partialDelivery: 'Da',
      totalBlockage: '40 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '876512308',
      client: 'Furnizor SudEst',
      agent: 'Dan Vasile',
      data: '12 Iunie 2025',
      zone: 'Giurgiu',
      status: 'În așteptare',
      reason: 'Validare financiară',
      responsive: 'Lucian Enache',
      lockDuration: '18 min',
      partialDelivery: 'Nu',
      totalBlockage: '18 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
          warning: true,
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '876512309',
      client: 'AgroMix Import',
      agent: 'Cristina Marin',
      data: '13 Iunie 2025',
      zone: 'Călărași',
      status: 'Finalizat',
      reason: '-',
      responsive: 'Irina Moise',
      lockDuration: '0 min',
      partialDelivery: 'Nu',
      totalBlockage: '0 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
    {
      orderNumber: '876512310',
      client: 'UtilAgro Furnizor',
      agent: 'Alexandra Dinu',
      data: '14 Iunie 2025',
      zone: 'Ploiești',
      status: 'Blocat',
      reason: 'Aviz neconform',
      responsive: 'Victor Dragu',
      lockDuration: '25 min',
      partialDelivery: 'Da',
      totalBlockage: '65 min',
      orderDetails: [
        {
          positionNumber: '#1',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#2',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#3',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#4',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#5',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#6',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#7',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#8',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#9',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#10',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#11',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#12',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#13',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#14',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
        {
          positionNumber: '#15',
          materialCode: '4235452',
          materialName: 'Tratament sămânță PRIMSEED MULTI, 10 L',
          quantity: '3',
          um: 'unitati',
          logisticUnity: 'Brasov',
          stock: '15',
        },
      ],
    },
  ];
  purchasesTitle: string = 'Achizitii';
  selectedTableRow: TableData | null = null;
  onTableRowClicked(data: TableData) {
    this.selectedTableRow = data;
  }
  onCloseSidebar(event: boolean) {
    this.selectedTableRow = null;
  }
}
