name: Deploy Angular App to Azure Static Web Apps (Production)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.19.0 (for Angular 20 compatibility)
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app (prod)
        run: npm run build:prod

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"
          output_location: "dist/agricover-dashboard/browser"
