name: Deploy Angular App to Azure Static Web Apps (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy-angular:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.19.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app (prod)
        run: npm run build:prod

      - name: Verify build output
        run: ls -R dist

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v2
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"
          output_location: \"./\"
          skip_app_build: true
          api_location: ""
          deployment_action: 'upload'
